platform :ios, '8.0'
inhibit_all_warnings!
use_frameworks!

target 'BlazeFlow_Login' do
    pod 'Blaze'
end

target 'BlazeFlow_Simple' do
    pod 'Blaze'
end

target 'BlazeFlow_Tree' do
    pod 'Blaze'
end

target 'BlazeFlow_Navigation' do
    pod 'Blaze'
end
